import { describe, expect, it } from "vitest";
import { GitHubClient, GitHubError } from "@/lib/github/client";
import { analyzeRepository } from "@/lib/repo/analyze";
import { gitBlobSha, json, mockGitHub, SHA } from "../fixtures/mock-github";

const sampleFiles = [
  { path: "README.md", content: "# Demo\n\nHello\n" },
  { path: "src/index.ts", content: "export function f(a: number) {\n  if (a > 1 && a < 5) return 1;\n  return 0;\n}\n" },
  { path: "src/util/math.py", content: "def add(a, b):\n    return a + b\n" },
  { path: "src/gen.ts", content: "// @generated by tool\nexport const x = 1;\n" },
  { path: "node_modules/x/index.js", content: "module.exports = 1;\n" },
  { path: "pnpm-lock.yaml", content: "lockfileVersion: 9\n" },
  { path: "assets/logo.png", content: "\u0000PNG" },
  { path: "data/blob.txt", content: "abc\u0000def" },
  { path: "link", content: "src/index.ts", mode: "120000" },
];

function analyze(fetchImpl: typeof fetch, opts: Parameters<typeof analyzeRepository>[2]["limits"] = {}, token = "t") {
  const stages: string[] = [];
  const client = new GitHubClient({ token, fetchImpl });
  return {
    stages,
    client,
    run: () => analyzeRepository("acme", "demo", { client, limits: opts, onStage: (s) => stages.push(s), now: () => new Date("2026-02-01T00:00:00Z") }),
  };
}

describe("analyzeRepository", () => {
  it("builds an accurate snapshot with exact sizes, lines and exclusions", async () => {
    const { fetchImpl, calls } = mockGitHub({
      files: sampleFiles,
      commits: [
        { sha: "b".repeat(40), date: "2026-01-02T00:00:00Z", files: ["src/index.ts"] },
        { sha: "c".repeat(40), date: "2025-12-01T00:00:00Z", files: ["src/index.ts", "README.md", "src/removed.ts"] },
      ],
    });
    const { run, stages } = analyze(fetchImpl);
    const snap = await run();

    expect(snap.revision).toEqual({ sha: SHA, ref: "main", committedAt: "2026-01-02T00:00:00Z" });
    expect(snap.files.map((f) => f.path)).toEqual(["README.md", "data/blob.txt", "src/index.ts", "src/util/math.py"]);
    const index = snap.files.find((f) => f.path === "src/index.ts")!;
    expect(index.lines).toBe(4);
    expect(index.size).toBe(new TextEncoder().encode(sampleFiles[1]!.content).length);
    expect(index.language).toBe("typescript");
    expect(index.complexity).toBe(3); // 1 + if + &&
    expect(index.commits).toBe(2);
    expect(index.lastModified).toBe("2026-01-02T00:00:00Z");

    const readme = snap.files.find((f) => f.path === "README.md")!;
    expect(readme.complexity).toBeNull();
    expect(readme.commits).toBe(1);
    expect(readme.lastModified).toBe("2025-12-01T00:00:00Z");

    const math = snap.files.find((f) => f.path === "src/util/math.py")!;
    expect(math.commits).toBe(0);
    expect(math.lastModified).toBeNull();

    const blob = snap.files.find((f) => f.path === "data/blob.txt")!;
    expect(blob.lines).toBeNull();
    expect(blob.linesNote).toBe("binary");

    expect(snap.excluded.byReason).toEqual({ directory: 1, lockfile: 1, "binary-or-asset": 1, symlink: 1, generated: 1 });
    expect(snap.lines).toEqual({ counted: 3, total: 4, stoppedEarly: false });
    expect(snap.activity).toMatchObject({ commits: 2, newest: "2026-01-02T00:00:00Z", oldest: "2025-12-01T00:00:00Z", partial: false });
    expect(stages).toEqual(["connect", "structure", "contents", "history", "complete"]);
    // Only fixed GitHub hosts are contacted.
    expect(calls.every((c) => c.startsWith("api.github.com/") || c.startsWith("codeload.github.com/"))).toBe(true);
  });

  it("records blob SHAs and resolves imports between included files", async () => {
    const files = [
      { path: "src/app.ts", content: 'import { util } from "./util";\nimport React from "react";\nimport gen from "./gen";\n' },
      { path: "src/util.ts", content: "export const util = 1;\n" },
      { path: "src/gen.ts", content: "// @generated\nexport default 1;\n" },
      { path: "py/pkg/__init__.py", content: "" },
      { path: "py/pkg/main.py", content: "from . import helpers\nimport os\n" },
      { path: "py/pkg/helpers.py", content: "X = 1\n" },
    ];
    const { fetchImpl } = mockGitHub({ files });
    const snap = await analyze(fetchImpl).run();
    const idx = (p: string) => snap.files.findIndex((f) => f.path === p);
    expect(snap.files[idx("src/util.ts")]!.blob).toBe(gitBlobSha(files[1]!.content));
    expect(snap.imports!.edges).toEqual(
      [
        [idx("py/pkg/main.py"), idx("py/pkg/helpers.py")],
        [idx("src/app.ts"), idx("src/util.ts")],
      ].sort((a, b) => a[0]! - b[0]!),
    );
    // "./gen" points at a generated (excluded) file: unresolved, not invented.
    expect(snap.imports).toMatchObject({ external: 2, unresolved: 1, truncated: false });
  });

  it("analyzes a specific ref and labels the revision with it", async () => {
    const { fetchImpl, calls } = mockGitHub({ files: sampleFiles.slice(0, 2) }, {
      "/repos/acme/demo/commits/v1.0.0": () => json({ sha: SHA, commit: { committer: { date: "2025-06-01T00:00:00Z" } } }),
    });
    const client = new GitHubClient({ token: "t", fetchImpl });
    const snap = await analyzeRepository("acme", "demo", { client, ref: "v1.0.0", limits: { commitWindow: 0 } });
    expect(snap.revision).toEqual({ sha: SHA, ref: "v1.0.0", committedAt: "2025-06-01T00:00:00Z" });
    expect(calls).toContain("api.github.com/repos/acme/demo/commits/v1.0.0");
  });

  it("reports a missing or private repository as not found", async () => {
    const { fetchImpl } = mockGitHub({ files: [] }, { "/repos/acme/demo": () => json({ message: "Not Found" }, 404) });
    await expect(analyze(fetchImpl).run()).rejects.toMatchObject({ code: "not_found" });
  });

  it("refuses repositories flagged private even if the token can read them", async () => {
    const { fetchImpl } = mockGitHub({ files: sampleFiles, private: true });
    await expect(analyze(fetchImpl).run()).rejects.toMatchObject({ code: "not_found" });
  });

  it("reports empty repositories", async () => {
    const { fetchImpl } = mockGitHub({ files: [] }, { "/repos/acme/demo/commits/main": () => json({ message: "Git Repository is empty." }, 409) });
    await expect(analyze(fetchImpl).run()).rejects.toMatchObject({ code: "empty" });
  });

  it("surfaces rate limits with a retry time", async () => {
    const reset = Math.floor(Date.now() / 1000) + 600;
    const { fetchImpl } = mockGitHub({ files: [] }, {
      "/repos/acme/demo": () => json({ message: "API rate limit exceeded" }, 403, { "x-ratelimit-remaining": "0", "x-ratelimit-reset": String(reset) }),
    });
    const err = (await analyze(fetchImpl).run().catch((e) => e)) as GitHubError;
    expect(err.code).toBe("rate_limited");
    expect(err.retryAt).toBe(reset * 1000);
  });

  it("maps 5xx and network failures to friendly errors", async () => {
    const a = mockGitHub({ files: [] }, { "/repos/acme/demo": () => json({}, 502) });
    await expect(analyze(a.fetchImpl).run()).rejects.toMatchObject({ code: "upstream" });
    const b = mockGitHub({ files: [] }, { "/repos/acme/demo": () => { throw new TypeError("fetch failed"); } });
    await expect(analyze(b.fetchImpl).run()).rejects.toMatchObject({ code: "network" });
  });

  it("times out slow requests", async () => {
    const { fetchImpl } = mockGitHub({ files: [] }, {
      "/repos/acme/demo": (_u, init) =>
        new Promise((_, reject) => init?.signal?.addEventListener("abort", () => reject(init.signal!.reason))),
    });
    const client = new GitHubClient({ fetchImpl, timeoutMs: 50 });
    await expect(analyzeRepository("acme", "demo", { client })).rejects.toMatchObject({ code: "timeout" });
  });

  it("discloses truncated trees", async () => {
    const { fetchImpl } = mockGitHub({ files: sampleFiles.slice(0, 3), truncated: true });
    const snap = await analyze(fetchImpl).run();
    expect(snap.tree.truncated).toBe(true);
    expect(snap.notes.join(" ")).toMatch(/truncated/);
  });

  it("keeps the city when contents cannot be downloaded, marking lines unavailable", async () => {
    const { fetchImpl } = mockGitHub({ files: sampleFiles.slice(0, 3) }, { [`/repos/acme/demo/tarball/${SHA}`]: () => json({}, 500) });
    const snap = await analyze(fetchImpl).run();
    expect(snap.files.every((f) => f.lines === null && f.linesNote === "not-fetched")).toBe(true);
    expect(snap.lines.counted).toBe(0);
    expect(snap.notes.join(" ")).toMatch(/line counts are unavailable/);
  });

  it("refuses redirects to unexpected hosts", async () => {
    const { fetchImpl, calls } = mockGitHub({ files: sampleFiles.slice(0, 2) }, {
      [`/repos/acme/demo/tarball/${SHA}`]: () => new Response(null, { status: 302, headers: { location: "https://evil.example.com/x.tgz" } }),
    });
    const snap = await analyze(fetchImpl).run();
    expect(calls.some((c) => c.includes("evil"))).toBe(false);
    expect(snap.lines.counted).toBe(0);
  });

  it("marks oversized files and honours the content budget", async () => {
    const big = { path: "big.ts", content: "x\n".repeat(600) };
    const { fetchImpl } = mockGitHub({ files: [big, ...sampleFiles.slice(0, 2)] });
    const snap = await analyze(fetchImpl, { maxFileBytesForLines: 1000 }).run();
    expect(snap.files.find((f) => f.path === "big.ts")).toMatchObject({ lines: null, linesNote: "too-large" });
    expect(snap.files.find((f) => f.path === "README.md")!.lines).toBe(3);

    const many = Array.from({ length: 400 }, (_, i) => ({ path: `src/f${String(i).padStart(3, "0")}.ts`, content: `export const v = ${i * 7919};\n`.repeat(20 + (i % 13)) }));
    const budget = mockGitHub({ files: many, tarChunk: 64 });
    const stopped = await analyze(budget.fetchImpl, { tarballMaxBytes: 256 }).run();
    expect(stopped.lines.stoppedEarly).toBe(true);
    expect(stopped.lines.counted).toBeLessThan(400);
    const notCounted = stopped.files.filter((f) => f.lines === null);
    expect(notCounted.length).toBeGreaterThan(0);
    expect(notCounted.every((f) => f.linesNote === "budget")).toBe(true);
    expect(stopped.notes.join(" ")).toMatch(/budget/);
  });

  it("degrades gracefully when commit history is rate limited", async () => {
    const { fetchImpl } = mockGitHub({ files: sampleFiles.slice(0, 2) }, {
      "/repos/acme/demo/commits": () => json({ message: "rate" }, 429, { "retry-after": "60" }),
    });
    const snap = await analyze(fetchImpl).run();
    expect(snap.activity).toBeNull();
    expect(snap.files.every((f) => f.commits === null)).toBe(true);
    expect(snap.notes.join(" ")).toMatch(/rate limit/);
  });

  it("uses a smaller commit window without a token", async () => {
    const commits = Array.from({ length: 8 }, (_, i) => ({ sha: String(i).repeat(40).slice(0, 40).replace(/./g, String(i % 10)), date: `2026-01-0${i + 1}T00:00:00Z`, files: ["README.md"] }));
    const { fetchImpl, calls } = mockGitHub({ files: sampleFiles.slice(0, 1), commits });
    await analyze(fetchImpl, {}, "").run();
    expect(calls.find((c) => c.includes("/commits?"))).toContain("per_page=5");
  });

  it("rejects repositories above the file limit", async () => {
    const files = Array.from({ length: 30 }, (_, i) => ({ path: `f${i}.ts`, content: "x" }));
    const { fetchImpl } = mockGitHub({ files });
    await expect(analyze(fetchImpl, { maxIncludedFiles: 20 }).run()).rejects.toMatchObject({ code: "too_large" });
  });

  it("handles large trees within a reasonable time", async () => {
    const files = Array.from({ length: 20_000 }, (_, i) => ({ path: `pkg${i % 40}/dir${i % 7}/file${i}.ts`, content: `export const v${i} = ${i};\n` }));
    const { fetchImpl } = mockGitHub({ files });
    const t0 = performance.now();
    const snap = await analyze(fetchImpl, { commitWindow: 0 }).run();
    expect(snap.files).toHaveLength(20_000);
    expect(snap.lines.counted).toBe(20_000);
    expect(performance.now() - t0).toBeLessThan(10_000);
  }, 20_000);
});
