import { describe, expect, it } from "vitest";
import { countLines, estimateComplexity, isBinary } from "@/lib/repo/metrics";
import { detectLanguage } from "@/lib/repo/languages";
import { exclusionReason, hasGeneratedMarker } from "@/lib/repo/exclusions";

const enc = (s: string) => new TextEncoder().encode(s);

describe("countLines", () => {
  it.each([
    ["", 0],
    ["a", 1],
    ["a\n", 1],
    ["a\nb", 2],
    ["a\nb\n", 2],
    ["\n\n\n", 3],
    ["a\r\nb\r\n", 2],
  ])("%j → %d", (s, n) => expect(countLines(enc(s))).toBe(n));
});

describe("isBinary", () => {
  it("detects NUL bytes", () => {
    expect(isBinary(new Uint8Array([65, 0, 66]))).toBe(true);
    expect(isBinary(enc("plain text"))).toBe(false);
  });
});

describe("estimateComplexity", () => {
  it("counts decision points in C-like code, ignoring comments and strings", () => {
    const src = `
      // if this comment counted it would be wrong
      function f(a, b) {
        if (a && b) { return "if while for"; }
        for (const x of a) { while (x) {} }
        switch (a) { case 1: break; case 2: break; }
        try {} catch (e) {}
        /* if */
        return a || b;
      }`;
    // 1 + if + && + for + while + case + case + catch + || = 9
    expect(estimateComplexity(src, "c")).toBe(9);
  });

  it("counts Python decision points", () => {
    const src = `def f(a):\n    # if comment\n    if a and not b:\n        pass\n    elif a or b:\n        pass\n    s = """if for while"""\n    for x in a:\n        pass\n`;
    // 1 + if + and + elif + or + for = 6
    expect(estimateComplexity(src, "hash")).toBe(6);
  });

  it("is unavailable for unsupported families", () => {
    expect(estimateComplexity("<div>if</div>", "none")).toBeNull();
  });
});

describe("languages and exclusions", () => {
  it.each([
    ["src/a.ts", "typescript"],
    ["src/a.TSX", "typescript"],
    ["lib/x.py", "python"],
    ["Dockerfile", "shell"],
    ["README", "other"],
    [".gitignore", "config"],
    [".env", "config"],
    ["LICENSE-MIT", "text"],
    ["Dockerfile.dev", "shell"],
  ])("%s → %s", (p, lang) => expect(detectLanguage(p)).toBe(lang));

  it.each([
    ["node_modules/react/index.js", "directory"],
    ["packages/a/dist/index.js", "directory"],
    ["pnpm-lock.yaml", "lockfile"],
    ["web/yarn.lock", "lockfile"],
    ["assets/logo.png", "binary-or-asset"],
    ["static/jquery.min.js", "minified"],
    ["api/foo.pb.go", "generated"],
    ["src/index.ts", null],
    ["docs/build-guide.md", null],
  ])("%s → %s", (p, reason) => expect(exclusionReason(p)).toBe(reason));

  it("supports custom configs", () => {
    expect(exclusionReason("fixtures/a.ts", { directories: ["fixtures"], filenames: [], extensions: [], suffixes: [] })).toBe("directory");
  });

  it("detects generated markers", () => {
    expect(hasGeneratedMarker("// Code generated by protoc. DO NOT EDIT.")).toBe(true);
    expect(hasGeneratedMarker("/* @generated */")).toBe(true);
    expect(hasGeneratedMarker("export const a = 1;")).toBe(false);
  });
});
